대격변
dev-newbie-randy/ShowMeTheBusStop pull request #12
Opened 2020-02-12 04:55 UTC by dev-newbie-randy

- 리뷰하기 번거롭게 하여 죄송합니다. (_ _)

2020-02-13 15:35 UTC, 2giwon requested changes

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance"
이건 어떤동작을 하는 건가요? 궁금합니다.

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/AndroidManifest.xml
> +            android:authorities="kr.pe.randy.StationSuggestionProvider" />
이건 무슨 역할을 하는건가요? 궁금합니다.

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/MainActivity.kt
> +        viewPager.reduceDragSensitivity()
이건 어떤 동작을 하는 코드 인가요? 궁금합니다.

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/data/entity/FavoriteStation.kt
> +    @PrimaryKey(autoGenerate = false)
autogenerate를 false로 하신 이유가 있나요?

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/view/adapter/BusStationListAdapter.kt
> +            .toString()
확장함수로 빼서 사용하면 중복코드를 없앨 수 있습니다.

2020-02-13 15:35 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/KinPresenter.kt
> +                    showFavorites(list)
프레젠터에는 안드로이드 플랫폼과 연관된 코드가 있으면 안됩니다. 여기서 라이브데이터로 옵저빙하는 건 좋지 않은 방법 같습니다.

2020-02-14 01:27 UTC, Devinear commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance"
저도 궁금합니다.

2020-02-14 01:29 UTC, Devinear commented on app/src/main/java/kr/pe/randy/showmethebusstop/data/entity/FavoriteStation.kt
> +    @PrimaryKey(autoGenerate = false)
autoGenerate의 값은 명시하지 않을 경우 Default가 False이지 않나요?

2020-02-14 01:31 UTC, Devinear approved these changes
대격변!!!

2020-02-14 03:38 UTC, dev-newbie-randy commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance"
헤헤 비밀인데..

2020-02-14 03:39 UTC, dev-newbie-randy commented on app/src/main/AndroidManifest.xml
> +            android:authorities="kr.pe.randy.StationSuggestionProvider" />
비밀2

2020-02-14 03:39 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/data/entity/FavoriteStation.kt
> +    @PrimaryKey(autoGenerate = false)
이런 게 있다는 것을 까먹지 않기 위함입니닷

2020-02-14 03:42 UTC, dev-newbie-randy commented on app/src/main/AndroidManifest.xml
> +            android:launchMode="singleInstance"
하나의 activity에서 StationSuggestionProvider의 역할을 수행하기 위함입니다.

2020-02-14 03:42 UTC, dev-newbie-randy commented on app/src/main/AndroidManifest.xml
> +            android:authorities="kr.pe.randy.StationSuggestionProvider" />
searchView의 recent history 기능 구현 부분입니다.

2020-02-14 03:43 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/MainActivity.kt
> +        viewPager.reduceDragSensitivity()
fling의 민감성을 개선한 부분입니다.
(예를 들면 vertical 방향의 scrolling을 기대했는데 의도치 않게 horizontal로 침범해서 viewpager가 동작한다든지...)

2020-02-14 03:50 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/KinPresenter.kt
> +                    showFavorites(list)
왜 안되는지 이유가 궁금합니다.

2020-02-16 12:34 UTC, 2giwon approved these changes

2020-02-18 10:35 UTC, merged