Feature retrofit 머지
dev-newbie-randy/ShowMeTheBusStop pull request #5
Opened 2020-01-22 01:11 UTC by dev-newbie-randy

버스 노선 찾기는 volley 를 유지하고 버스 정류장 찾기만 retrofit 으로 변경

2020-01-22 05:23 UTC, 2giwon requested changes

2020-01-22 05:23 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/network/Parser.kt
>  class Parser {
class를 없애고 아래 compaion도 없애고 Object로 선언해도 될 것 같습니다.

2020-01-22 05:23 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/fragment/BusStationFragment.kt
>          (recyclerView.adapter as BusStationListAdapter).setEntries(list)
bindList는 아이템을 bind할 것 같은데 다른 동작이 들어 있습니다. 
다른 함수로 빼던지 아니면 list가 empty일 때를 다른곳에서 에러처리를 하는 것이 나아 보입니다.

2020-01-22 05:23 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/adapter/BusStationListAdapter.kt
> +    var onItemClick: ((BusStation) -> Unit)? = null
onItemClick을 주생성자로 val로 넣으면 var로 선언하지 않아도 적용할 수 있을거 같아요

2020-01-25 03:51 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/network/Parser.kt
>  class Parser {
좋은 의견입니다.

2020-01-25 03:52 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/fragment/BusStationFragment.kt
>          (recyclerView.adapter as BusStationListAdapter).setEntries(list)
이것은 UI쪽에서 empty인지 아닌지 판단하지 않으려고 이렇게 해둔 것입니다. 검색된 결과가 없으면 메시지를 보여주면서 기존 리스트를 없애줘야 하기 때문에 현재 상태를 유지하는 게 나을 거 같습니다.

2020-01-25 03:56 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/adapter/BusStationListAdapter.kt
> +    var onItemClick: ((BusStation) -> Unit)? = null
좋은 의견입니다.

2020-01-27 11:30 UTC, closed without merging