Feature mvp
dev-newbie-randy/ShowMeTheBusStop pull request #6
Opened 2020-01-28 05:51 UTC by dev-newbie-randy

route list도 mvp로 구조변경

2020-01-30 07:49 UTC, Devinear approved these changes

2020-02-03 04:03 UTC, 2giwon requested changes

2020-02-03 04:03 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/model/StationApi.kt
>                  level = HttpLoggingInterceptor.Level.BODY
디버깅과 릴리즈 때 다른 레벨 값을 전달 하는 것을 추천드립니다.

2020-02-03 04:03 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/RouteContract.kt
> +        fun onSuccess(list: List<RouteData>)
contract에 리스너 말고 요청함수에 고차함수로 던지는 방법으로 하는게 어떨까요?

2020-02-03 04:03 UTC, 2giwon commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/RoutePresenter.kt
> +        searchView ?: return
앨비스 연산자로 널일때 리턴하는 것보다

?. let 이나 run을 사용하는게 어떨까요?

2020-02-04 01:33 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/RoutePresenter.kt
> +        searchView ?: return
그러는 게 더 나아보입니다. 수정하였습니다.

2020-02-04 01:44 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/model/StationApi.kt
>                  level = HttpLoggingInterceptor.Level.BODY
의견 적극수렴하여 반영하였습니다.

2020-02-04 02:41 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/model/StationApi.kt
>                  level = HttpLoggingInterceptor.Level.BODY
d86f455d041080b494682f6e8cf010ed0fb41e60

2020-02-04 02:44 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/RoutePresenter.kt
> +        searchView ?: return
334d96ffc302397bbebc6ec9d6a5b9dc45f091f0

2020-02-04 02:44 UTC, dev-newbie-randy commented on app/src/main/java/kr/pe/randy/showmethebusstop/presenter/RouteContract.kt
> +        fun onSuccess(list: List<RouteData>)
Feature mvp 에서는 현 상태 유지하겠습니다. 고차함수에 대한 스터디 후에 적용 검토하겠습니다.

2020-02-04 04:38 UTC, 2giwon approved these changes

2020-02-04 05:34 UTC, merged